# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

flutter_application_path = '../my_flutter/'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'NativeToFlutter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  install_all_flutter_pods(flutter_application_path)

  # Pods for NativeToFlutter

end
